title: Telary - Your data. Ready for AI.
description: Telary propose une data platform clé en main, 100% open source, déployée en 24h, pour aider les startups et PME à exploiter pleinement leurs données.
baseurl: ""
url: "https://telary.io"
permalink: /:title/
collections:
  posts:
    output: true
    permalink: /posts/:title/

# GitHub Pages configuration
github: [metadata]
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot

# Polyglot configuration
languages: ["fr", "en"]
default_lang: "en"
exclude_from_localizations:
  [
    "assets",
    "images",
    "js",
    "css",
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor",
  ]
parallel_localization: true
lang_from_path: true

sass:
  sourcemap: never
