title: Telary - Data Platform Open Source pour Startups et PME
description: Telary propose une data platform clé en main, 100% open source, déployée en 24h, pour aider les startups et PME à exploiter pleinement leurs données.
baseurl: ""
url: "https://telary.io"
permalink: /:title/
collections:
  posts:
    output: true
    permalink: /posts/:title/

# GitHub Pages configuration
github: [metadata]
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
