title: Telary - Data made Agile
description: Let's build your data platform
baseurl: ""
url: "https://telary.io"
collections:
  posts:
    output: true
permalink: /:title/

# GitHub Pages configuration
github: [metadata]
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 